version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    container_name: url-shorter
    volumes:
      - .:/django_url_shortener
    ports:
      - "80:8000"